name: mplsoccer-dev
channels:
  - anaconda
  - conda-forge
dependencies:
  - jupyter
  - pandas
  - scipy
  - seaborn
  - sphinx
  - pyarrow
  - beautifulsoup4
  - lxml
  - setuptools
  - twine
  - conda-forge::ffmpeg
  - pillow
  - sphinx-gallery
  - sphinx_rtd_theme
  - numpydoc
  - wheel
  - pip
  - pip:
      - -e .
